# -*- coding: utf-8 -*-
"""
AKC_SIH_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pEgGbgxYb4z31K77ZSbqkmncAle0r6Xw
"""

# SETUP
# Core ML and vision packages (PyTorch, TorchVision)
# !pip install --upgrade torch torchvision torchaudio --quiet
# Basic computer vision tools
# !pip install opencv-python pillow matplotlib --quiet
# Utilities for progress bar
# !pip install tqdm --quiet

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
import torch.optim.lr_scheduler as lr_scheduler
from PIL import Image, UnidentifiedImageError
import xml.etree.ElementTree as ET
from sklearn.model_selection import train_test_split
from glob import glob
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.metrics import classification_report


# DATA COLLECTION AND INGESTION
def load_data():
    """
    Load and process image-label pairs from XML files
    """
    # Define paths based on the structure
    GDRIVE_ROOT = '/content/drive/MyDrive/SIH_AKC_PROJECT'
    EMDS7_ROOT = os.path.join(GDRIVE_ROOT, 'EMDS7')
    IMAGE_FOLDER = os.path.join(EMDS7_ROOT, 'EMDS7Img')
    XML_FOLDER = os.path.join(EMDS7_ROOT, 'EMDS7xml')

    print(f"Attempting to find images in: {IMAGE_FOLDER}")
    print(f"Attempting to find XML files in: {XML_FOLDER}")

    # Load image paths
    img_extensions = ('.jpg', '.jpeg', '.png', '.bmp', '.tif')
    image_paths = []
    for ext in img_extensions:
        image_paths.extend(glob(os.path.join(IMAGE_FOLDER, f'**/*{ext}'), recursive=True))

    print(f"Total image files found: {len(image_paths)}")

    # Build a dictionary to map image filenames (without extension) to their full paths
    image_filename_to_path = {os.path.splitext(os.path.basename(img_path))[0]: img_path for img_path in image_paths}

    # Build a list of image-label pairs by processing XML files
    image_label_pairs = []
    class_names_set = set() # Use a set to store unique class names

    xml_files = glob(os.path.join(XML_FOLDER, '**/*.xml'), recursive=True)
    print(f"Total XML files found: {len(xml_files)}")

    for xml_file in xml_files:
        try:
            tree = ET.parse(xml_file)
            root = tree.getroot()

            # Extract image filename from XML (assuming it's in the <filename> tag)
            xml_filename_tag = root.find('filename')
            if xml_filename_tag is not None:
                xml_filename = os.path.splitext(xml_filename_tag.text)[0] # Get filename without extension
                # Correct the filename mismatch: replace EMDS6- with EMDS7-
                corrected_xml_filename = xml_filename.replace('EMDS6-', 'EMDS7-')

                # Find the corresponding image path using the corrected filename
                if corrected_xml_filename in image_filename_to_path:
                    img_path = image_filename_to_path[corrected_xml_filename]

                    # Extract class labels from XML (assuming object names are in <name> tags)
                    labels = []
                    for obj in root.findall('object'):
                        name = obj.find('name')
                        if name is not None:
                            class_name = name.text
                            labels.append(class_name)
                            class_names_set.add(class_name) # Add to set of class names

                    # Assuming each image has a single main label, take the first one found
                    if labels:
                        image_label_pairs.append((img_path, labels[0])) # Append the first label found
                    else:
                        # Handle cases where an XML might not have an object (though less likely for this dataset)
                        print(f"Warning: No object found in XML file: {xml_file}")

        except Exception as e:
            print(f"Error processing XML file {xml_file}: {e}")

    # Convert set of class names to a sorted list and create a mapping
    class_names = sorted(list(class_names_set))
    class_to_idx = {class_name: i for i, class_name in enumerate(class_names)}

    print(f"Classes found: {class_names}")
    print(f"Total labeled images (matched with XML): {len(image_label_pairs)}")
    
    return image_label_pairs, class_to_idx, class_names


# PYTORCH DATASET AND DATA LOADER
class EMDS7Dataset(Dataset):
    def __init__(self, image_label_pairs, class_to_idx, transform=None):
        self.image_label_pairs = image_label_pairs
        self.class_to_idx = class_to_idx
        self.transform = transform

    def __len__(self):
        return len(self.image_label_pairs)

    def __getitem__(self, idx):
        img_path, label_name = self.image_label_pairs[idx]
        try:
            img = Image.open(img_path).convert('RGB') # Ensure image is in RGB format
            if self.transform:
                img = self.transform(img)

            label_idx = self.class_to_idx[label_name] # Convert label name to index
            return img, label_idx
        except (UnidentifiedImageError, FileNotFoundError) as e:
            print(f"Warning: Could not read image file: {img_path}. Error: {e}. Skipping.")
            return None, None


# Custom collate function to handle None values from skipped images
def collate_fn(batch):
    batch = list(filter(lambda x: x is not None and x[0] is not None, batch))
    if not batch:
        return None, None
    return torch.utils.data.dataloader.default_collate(batch)


def create_data_loaders(image_label_pairs, class_to_idx):
    """
    Create train and validation data loaders
    """
    # Define transformations
    IMG_SIZE = 224

    # Transformations for training with augmentation
    train_transform = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.RandomRotation(degrees=10), # Random rotation
        transforms.RandomHorizontalFlip(p=0.5), # Random horizontal flip
        transforms.RandomVerticalFlip(p=0.5),   # Random vertical flip
        transforms.RandomCrop(IMG_SIZE, padding=4), # Random crop
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1), # Color jitter
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406],
                             [0.229, 0.224, 0.225])
    ])

    # Transformations for validation (no augmentation)
    val_transform = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406],
                             [0.229, 0.224, 0.225])
    ])

    # Split into train/val set
    train_pairs, val_pairs = train_test_split(image_label_pairs, test_size=0.2, random_state=42)

    train_ds = EMDS7Dataset(train_pairs, class_to_idx, train_transform)
    val_ds = EMDS7Dataset(val_pairs, class_to_idx, val_transform)

    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, num_workers=2, collate_fn=collate_fn)
    val_loader = DataLoader(val_ds, batch_size=32, shuffle=False, num_workers=2, collate_fn=collate_fn)

    print(f"Train dataset size: {len(train_ds)}")
    print(f"Validation dataset size: {len(val_ds)}")
    
    return train_loader, val_loader, train_ds, val_ds


# MODEL SETUP
def create_pretrained_model(num_classes, model_name="mobilenet_v2"):
    """
    Loads a pretrained CNN model and modifies its final classification layer.

    Args:
        num_classes (int): The number of output classes for the final layer.
        model_name (str): The name of the pretrained model to load.
                          Supported models: 'mobilenet_v2', 'resnet18', 'resnet50'.

    Returns:
        torch.nn.Module: The configured pretrained model.
        None: If an unsupported model_name is provided.
    """
    if model_name == "mobilenet_v2":
        # Using weights parameter as recommended
        model = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.IMAGENET1K_V1)
        # Modify the classifier
        model.classifier[1] = nn.Linear(model.last_channel, num_classes)
    elif model_name == "resnet18":
         # Using weights parameter as recommended
        model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)
        # Modify the fully connected layer
        num_ftrs = model.fc.in_features
        model.fc = nn.Linear(num_ftrs, num_classes)
    elif model_name == "resnet50":
         # Using weights parameter as recommended
        model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
        # Modify the fully connected layer
        num_ftrs = model.fc.in_features
        model.fc = nn.Linear(num_ftrs, num_classes)
    else:
        print(f"Unsupported model name: {model_name}")
        return None

    return model


# TRAINING FUNCTIONS
def train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0
    correct = 0
    total = 0
    for imgs, labels in tqdm(loader, desc="Training"):
        # Handle potential None values from collate_fn for skipped images
        if imgs is None or labels is None:
            continue

        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * imgs.size(0)
        _, predicted = outputs.max(1)
        correct += predicted.eq(labels).sum().item()
        total += labels.size(0)
    # Avoid division by zero if total is 0 (e.g., if all images were skipped)
    avg_loss = running_loss / total if total > 0 else 0
    acc = correct / total if total > 0 else 0
    return avg_loss, acc

def eval_epoch(model, loader, criterion, device):
    model.eval()
    running_loss = 0
    correct = 0
    total = 0
    with torch.no_grad():
        for imgs, labels in tqdm(loader, desc="Validation"):
             # Handle potential None values from collate_fn for skipped images
            if imgs is None or labels is None:
                continue

            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            loss = criterion(outputs, labels)
            running_loss += loss.item() * imgs.size(0)
            _, predicted = outputs.max(1)
            correct += predicted.eq(labels).sum().item()
            total += labels.size(0)
    # Avoid division by zero if total is 0 (e.g., if all images were skipped)
    avg_loss = running_loss / total if total > 0 else 0
    acc = correct / total if total > 0 else 0
    return avg_loss, acc


def train_model(model, train_loader, val_loader, device, num_classes, gdrive_root):
    """
    Train the model with advanced techniques: learning rate scheduling, 
    model checkpointing, and early stopping
    """
    # Define criterion and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=1e-4)

    # Define a learning rate scheduler
    # Using ReduceLROnPlateau: Reduce learning rate when a metric has stopped improving.
    scheduler = lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.1, patience=5)

    # Model checkpointing and early stopping
    best_val_acc = 0.0
    epochs_no_improve = 0
    early_stop_patience = 10 # Number of epochs to wait for improvement before stopping

    # Define path for saving the best model
    BEST_MODEL_PATH = os.path.join(gdrive_root, 'best_model.pth')
    print(f"Best model will be saved to: {BEST_MODEL_PATH}")

    # Run training with scheduler, checkpointing, and early stopping
    EPOCHS = 15 # Increase number of epochs to allow for early stopping
    for epoch in range(EPOCHS):
        print(f"Epoch {epoch+1}/{EPOCHS}")

        # Pass criterion, optimizer, and device to training function
        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)
        # Pass criterion and device to evaluation function
        val_loss, val_acc = eval_epoch(model, val_loader, criterion, device)

        print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
        print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")

        # Step the scheduler based on validation accuracy
        scheduler.step(val_acc)

        # Check for best model and save checkpoint
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            epochs_no_improve = 0
            print(f"Validation accuracy improved. Saving model to {BEST_MODEL_PATH}")
            try:
                torch.save(model.state_dict(), BEST_MODEL_PATH)
            except Exception as e:
                print(f"Error saving model checkpoint: {e}")

        else:
            epochs_no_improve += 1
            print(f"Validation accuracy did not improve for {epochs_no_improve} epoch(s).")

        # Check for early stopping
        if epochs_no_improve >= early_stop_patience:
            print(f"Early stopping triggered after {epoch+1} epochs.")
            break

    print("Training finished.")
    return BEST_MODEL_PATH


# EVALUATION
def evaluate_model(model, val_loader, class_names, class_to_idx, device, best_model_path):
    """
    Evaluate the trained model on validation set
    """
    # Load the best model
    try:
        # Ensure the model is on the correct device before loading state_dict
        model.load_state_dict(torch.load(best_model_path, map_location=device))
        print(f"Successfully loaded model from {best_model_path}")
    except FileNotFoundError:
        print(f"Error: Model file not found at {best_model_path}")
    except Exception as e:
        print(f"Error loading model: {e}")

    # Define criterion
    criterion = nn.CrossEntropyLoss()

    print("\nEvaluating the model on the validation set...")
    model.eval()
    all_labels = []
    all_predictions = []
    running_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for imgs, labels in tqdm(val_loader, desc="Evaluating"):
            # Handle potential None values from collate_fn for skipped images
            if imgs is None or labels is None:
                continue

            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * imgs.size(0)
            _, predicted = outputs.max(1)

            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predicted.cpu().numpy())

            correct += predicted.eq(labels).sum().item()
            total += labels.size(0)

    avg_loss = running_loss / total if total > 0 else 0
    accuracy = correct / total if total > 0 else 0

    print(f"Validation Loss: {avg_loss:.4f}, Validation Accuracy: {accuracy:.4f}")

    # Print classification report
    print("\nClassification Report:")
    # Ensure target_names are in the correct order based on class_to_idx
    # We need to create a list of class names ordered by their index
    idx_to_class = {v: k for k, v in class_to_idx.items()}
    target_names_ordered = [idx_to_class[i] for i in sorted(idx_to_class.keys())]

    # Explicitly specify labels to include all possible classes
    all_possible_labels = list(class_to_idx.values())

    print(classification_report(all_labels, all_predictions, labels=all_possible_labels, target_names=target_names_ordered, zero_division=0))
    
    return idx_to_class


def test_on_random_images(model, image_label_pairs, class_to_idx, device, idx_to_class):
    """
    Test the model on a few random images
    """
    import random
    
    print("\nTesting on a few random images:")
    random_image_pairs = random.sample(image_label_pairs, min(5, len(image_label_pairs))) # Get up to 5 random images

    # Define val_transform
    IMG_SIZE = 224
    val_transform = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406],
                             [0.229, 0.224, 0.225])
    ])

    model.eval()
    with torch.no_grad():
        for img_path, true_label_name in random_image_pairs:
            try:
                img = Image.open(img_path).convert('RGB')
                img_tensor = val_transform(img).unsqueeze(0).to(device) # Use val_transform and add batch dimension

                outputs = model(img_tensor)
                _, predicted_idx = outputs.max(1)
                predicted_label_name = idx_to_class[predicted_idx.item()]

                print(f"Image: {os.path.basename(img_path)}, True Label: {true_label_name}, Predicted Label: {predicted_label_name}")

            except (UnidentifiedImageError, FileNotFoundError) as e:
                print(f"Warning: Could not read or process image file: {img_path}. Error: {e}. Skipping.")
            except Exception as e:
                 print(f"Error processing random image {img_path}: {e}")


# MAIN EXECUTION
def main():
    """
    Main function to execute the complete pipeline
    """
    # Mount Google Drive
    from google.colab import drive
    print("Attempting to mount Google Drive...")
    try:
        drive.mount('/content/drive', force_remount=True)
        print("Google Drive mounted successfully.")
    except Exception as e:
        print(f"Google Drive mount failed: {e}")

    # Load data
    image_label_pairs, class_to_idx, class_names = load_data()
    
    if not image_label_pairs:
        print("Error: No image-label pairs were created. Cannot proceed.")
        return

    # Set number of classes
    NUM_CLASSES = len(class_names)
    print(f"Number of classes: {NUM_CLASSES}")

    # Create data loaders
    train_loader, val_loader, train_ds, val_ds = create_data_loaders(image_label_pairs, class_to_idx)

    # Set device
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    # Create model
    model_name_to_use = "mobilenet_v2" # Change this to "resnet18" or "resnet50" to try other models
    model = create_pretrained_model(NUM_CLASSES, model_name_to_use)

    if model is None:
        print(f"Failed to load model: {model_name_to_use}")
        return

    model = model.to(device)
    print(f"Successfully loaded and configured {model_name_to_use} model.")
    print(f"Model on device: {device}")
    print(f"Number of output classes set to: {NUM_CLASSES}")

    # Train model
    GDRIVE_ROOT = '/content/drive/MyDrive/SIH_AKC_PROJECT'
    best_model_path = train_model(model, train_loader, val_loader, device, NUM_CLASSES, GDRIVE_ROOT)

    # Evaluate model
    idx_to_class = evaluate_model(model, val_loader, class_names, class_to_idx, device, best_model_path)

    # Test on random images
    test_on_random_images(model, image_label_pairs, class_to_idx, device, idx_to_class)


if __name__ == "__main__":
    main()